### ISSUE TITLE
About: Error: You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by mozgbrasil** [CeamKrier/steppify#1]
Hello Good morning my friends

I am testing your extension but the following error is being returned

Can you help me ?

    ERROR in ./~/steppify/src/jsx/StepContent.js
    Module parse failed: /project/frontend/node_modules/steppify/src/jsx/StepContent.js Unexpected token (13:6)
    You may need an appropriate loader to handle this file type.

![Captura de tela de 2019-10-09 11-24-51](https://user-images.githubusercontent.com/17202780/66490539-b2a2a980-ea87-11e9-8fad-24ade4db3ec3.png)

**Comment by CeamKrier** [comment]
Hey @mozgbrasil,

Thank you for pointing out the issue. I have checked it and updated the package for version 1.1.1.

Also, please be sure that your `webpack.config.js` has configured to handle CSS files. If you don't have the necessary config for it, check the screenshot below for the required configuration.

Run the command `npm i style-loader css-loader` and then add the rule as specified below:

![image](https://user-images.githubusercontent.com/18554425/66504445-c410a380-ead1-11e9-9fad-cfbbaf95d53d.png)

**Comment by CeamKrier** [comment]
I'm closing this issue.

If you face any obstacle while trying to use the module, feel free to re-open this issue.
